apiVersion: v2
name: virtual-secrets-server
description: A Helm chart for Virtual Secrets Server by AppsCode
type: application
version: v2025.3.14
appVersion: v0.0.1
home: https://virtual-secrets.dev
icon: https://cdn.appscode.com/images/products/kubevault/icons/android-icon-192x192.png
sources:
- https://github.com/virtual-secrets
maintainers:
- name: appscode
  email: support@appscode.com
dependencies:
- name: ace-user-roles
  repository: oci://ghcr.io/appscode-charts
  condition: ace-user-roles.enabled
  version: v2025.3.14
