
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: secretsources.meta.virtual-secrets.dev
spec:
  group: meta.virtual-secrets.dev
  names:
    categories:
    - meta
    - virtual-secrets
    - appscode
    kind: SecretSource
    listKind: SecretSourceList
    plural: secretsources
    shortNames:
    - scsource
    singular: secretsource
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.secretManager
      name: SecretManagerType
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SecretSourceSpec defines the desired state of SecretSource
            properties:
              vault:
                properties:
                  roleName:
                    description: Name of the vault role to use for the operator
                    type: string
                  url:
                    description: Connection url to the secret manager
                    type: string
                required:
                - url
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
