
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: secretmetadatas.meta.virtual-secrets.dev
spec:
  group: meta.virtual-secrets.dev
  names:
    categories:
    - meta
    - virtual-secrets
    - appscode
    kind: SecretMetadata
    listKind: SecretMetadataList
    plural: secretmetadatas
    shortNames:
    - scmetadata
    singular: secretmetadata
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: TYPE
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SecretMetadataSpec defines the desired state of SecretMetadata
            properties:
              secretSource:
                description: Name of the SecretSource object
                type: string
              type:
                default: Opaque
                description: 'Used to facilitate programmatic handling of secret data.
                  More meta: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types'
                type: string
            required:
            - secretSource
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
