apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "virtual-secrets.fullname" . }}
  labels:
    {{- include "virtual-secrets.labels" . | nindent 4 }}
rules:
- apiGroups:
  - virtual-secrets.dev
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["create"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  - serviceaccounts
  verbs: ["get", "list", "watch"]
